### ISSUE TITLE
Use Github actions to create automatic builds

### ISSUE THREAD

**Issue by vx-i** [dm-vodopyanov/py_inspect#4]
Hi,

I would like to ask if it is possible to create automatic builds with Github Actions? Or maybe even releases 👍 

Cheers
vx-i

**Comment by vasily-v-ryabov** [comment]
Hi @vx-i let's move this discussion to officially supported fork: https://github.com/pywinauto/py_inspect. Maybe I will unbind the fork from this master repo as it adds a lot of confusion. @dm-vodopyanov made a good job in his time, but now it's better to stop bothering him.

**Comment by vasily-v-ryabov** [comment]
Hi @dm-vodopyanov can I ask you to disable issues for this master repo? It's possible in repo settings if you wish.

**Comment by dm-vodopyanov** [comment]
Hi @vx-i, thank you so much for your interest in this project!:blush: Unfortunately, I don't have time to support this project. Could you please submit the same issue to https://github.com/pywinauto/py_inspect/issues?
Hi @vasily-v-ryabov, thanks, disabled. I will also add a note in README.md regarding this repo is not being supported any more, and will add a link to the officially supported repo - https://github.com/pywinauto/py_inspect.
